fix: secure workflows agains hackclaw attack (#240)
* fix: secure workflows agains hackclaw attack

* sanitize input string

diff --git a/.github/workflows/create_release.yml b/.github/workflows/create_release.yml
--- a/.github/workflows/create_release.yml
+++ b/.github/workflows/create_release.yml
@@ -21,6 +21,14 @@ jobs:
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
+      - name: Validate version
+        shell: bash
+        run: |
+          if [[ ! "${{ github.event.inputs.version_bump }}" =~ ^(major|minor|patch)$ ]]; then
+            echo "Invalid value: $v" >&2
+            exit 1
+          fi
+
       - uses: rymndhng/release-on-push-action@aebba2bbce07a9474bf95e8710e5ee8a9e922fe2 # v0.28.0
         id: tag-release
         with:
